# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 23:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='address_book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='address_set',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('fqdn', models.CharField(blank=True, max_length=256)),
                ('IP', models.GenericIPAddressField(unique=True)),
                ('mask', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='app_req',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pre', models.CharField(max_length=100, unique=True)),
                ('app_name', models.CharField(max_length=100)),
                ('app_env', models.CharField(max_length=100)),
                ('compartment', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='fw_req',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service', models.CharField(blank=True, max_length=100)),
                ('protocol', models.GenericIPAddressField()),
                ('action', models.BooleanField(default=True)),
                ('log', models.BooleanField(default=True)),
                ('scheduled', models.BooleanField(default=False)),
                ('schedule_date', models.DateField(default=datetime.datetime.today)),
                ('rule_desc', models.CharField(blank=True, max_length=100)),
                ('address_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.address_set')),
            ],
        ),
        migrations.CreateModel(
            name='gtm_req',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('wide_ip', models.CharField(blank=True, max_length=100)),
                ('mastersite', models.CharField(blank=True, max_length=100)),
                ('failoverstate', models.CharField(blank=True, max_length=100)),
                ('preferedbalance', models.CharField(blank=True, max_length=100)),
                ('altbalance', models.CharField(blank=True, max_length=100)),
                ('fallback', models.CharField(blank=True, max_length=100)),
                ('address_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.address_set')),
            ],
        ),
        migrations.CreateModel(
            name='ltm_req',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placehold_ip', models.CharField(max_length=128, unique=True)),
                ('port', models.IntegerField()),
                ('oneconnect', models.BooleanField(default=False)),
                ('http_compression', models.BooleanField(default=False)),
                ('requestlog', models.CharField(blank=True, max_length=256)),
                ('loadbalance', models.CharField(max_length=100)),
                ('healthmon', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='per_req',
            fields=[
                ('per', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('app_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.app_req')),
                ('fw_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.fw_req')),
                ('gtm_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.gtm_req')),
                ('ltm_req', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.ltm_req')),
            ],
        ),
        migrations.CreateModel(
            name='ssl_req',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ssl_fqdn', models.CharField(blank=True, max_length=256)),
                ('ssl_req', models.BooleanField(default=False)),
                ('ssl_cipher', models.CharField(blank=True, max_length=100)),
                ('mutauth', models.BooleanField(default=False)),
                ('datagroup', models.CharField(blank=True, max_length=100)),
                ('ma_client', models.CharField(blank=True, max_length=100)),
                ('ma_srv', models.CharField(blank=True, max_length=100)),
                ('ma_client_srv', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='per_req',
            name='ssl_req',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.ssl_req'),
        ),
        migrations.AddField(
            model_name='address_book',
            name='address_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.address_set'),
        ),
    ]
