# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 04:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_auto_20160619_0240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressbook',
            old_name='id',
            new_name='ab_id',
        ),
        migrations.RenameField(
            model_name='addressset',
            old_name='id',
            new_name='as_id',
        ),
        migrations.RenameField(
            model_name='applicationrequest',
            old_name='id',
            new_name='app_id',
        ),
        migrations.RenameField(
            model_name='firewallrequest',
            old_name='id',
            new_name='fw_id',
        ),
        migrations.RenameField(
            model_name='gtmrequest',
            old_name='id',
            new_name='gtm_id',
        ),
        migrations.RenameField(
            model_name='ltmrequest',
            old_name='id',
            new_name='ltm_id',
        ),
        migrations.RenameField(
            model_name='perrequest',
            old_name='perID',
            new_name='per_id',
        ),
        migrations.RenameField(
            model_name='sslrequest',
            old_name='id',
            new_name='ssl_id',
        ),
    ]
