# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0008_auto_20160619_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='addressset',
            name='port',
            field=models.CharField(default=80, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ltmrequest',
            name='node',
            field=models.ManyToManyField(to='request.AddressSet'),
        ),
    ]
