# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0009_auto_20160623_0506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ltmrequest',
            name='node',
        ),
        migrations.AddField(
            model_name='ltmrequest',
            name='AddressSet',
            field=models.ForeignKey(default=80, on_delete=django.db.models.deletion.CASCADE, to='request.AddressSet'),
            preserve_default=False,
        ),
    ]
