# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-23 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0010_auto_20160623_0515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gtmrequest',
            name='AddressSet',
        ),
        migrations.AddField(
            model_name='gtmrequest',
            name='AddressSet',
            field=models.ManyToManyField(to='request.AddressSet'),
        ),
        migrations.RemoveField(
            model_name='ltmrequest',
            name='AddressSet',
        ),
        migrations.AddField(
            model_name='ltmrequest',
            name='AddressSet',
            field=models.ManyToManyField(to='request.AddressSet'),
        ),
    ]
